CREATE TABLE  "ACCOUNT" 
   (	"AC_NUMBER" NUMBER, 
	"AC_TYPE" VARCHAR2(100) NOT NULL ENABLE, 
	"PIN_CODE" VARCHAR2(100), 
	"BALANCE" NUMBER, 
	"RFID" VARCHAR2(100), 
	"SECURITYCODE" VARCHAR2(100)
   )
/
CREATE TABLE  "CUSTOMER" 
   (	"CUST_NAME" VARCHAR2(100), 
	"ADDRESS" VARCHAR2(100), 
	"PHONE_NUMBER" VARCHAR2(100), 
	"CITY" VARCHAR2(100), 
	"EMAILID" VARCHAR2(100), 
	"AC_NUMBER" NUMBER
   )
/
CREATE TABLE  "HISTORYTRAN" 
   (	"HISTORYTRANID" NUMBER, 
	"SEQUENCEOP" VARCHAR2(200), 
	"TYPE" VARCHAR2(100), 
	"AC_NUMBER" NUMBER, 
	 CONSTRAINT "HISTORYTRAN_PK" PRIMARY KEY ("HISTORYTRANID") ENABLE
   )
/
CREATE TABLE  "TRANSACTION1" 
   (	"TR_NUMBER" NUMBER, 
	"AC_NUMBER" NUMBER, 
	"TDATE" VARCHAR2(100), 
	"TR_TYPE" VARCHAR2(100), 
	"AMOUNT" NUMBER
   )
/
CREATE UNIQUE INDEX  "HISTORYTRAN_PK" ON  "HISTORYTRAN" ("HISTORYTRANID")
/
 CREATE SEQUENCE   "HISTORYTRAN_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE
/
CREATE OR REPLACE TRIGGER  "BI_HISTORYTRAN" 
  before insert on "HISTORYTRAN"               
  for each row  
begin   
    select "HISTORYTRAN_SEQ".nextval into :NEW.HISTORYTRANID from dual; 
end; 

/
ALTER TRIGGER  "BI_HISTORYTRAN" ENABLE
/